[pytest]
test_paths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Критичные тесты для быстрой проверки
    regression: Полный набор регрессионных тестов
    api: API тесты
    ui: UI тесты
addopts = -v -s
          -- clean-alluredir